### ISSUE TITLE
ATIS-AFW Make "Comment/Arrangements" Text Area usable

### ISSUE THREAD

**Issue by GeheimagentNr1** [vatger/atciss#523]
It would be nice if text manually entered into the "Comment/Arrangements" Text Area would be saved.
Currently, if I change the page or click out of the "Comment/Arrangements" Text Area the text is reset to a default value.

Maybe the text value of the "Comment/Arrangements" Text Area can be saved to the local storage of the browser, so it is also saved if the web page is closed or the page is changed.

A button to reset the text to the default value would be good in this case.

**Comment by globin** [comment]
The text will be saved if you are on the ATC roster of VATGer and at least S2.

Frontend handling/display of the permission denied error is lacking though.

**Comment by GeheimagentNr1** [comment]
Why is it not working for S1 controllers?
Is it because the tool is mainly used on APP or CTR positions?

**Comment by fpletz** [comment]
The restriction was added so that trainees and users not actively controlling are still able to view ATCISS but are not able to change agreements. As we currently do not have any history for the agreements we want to ensure no trolling or edit wars happen. The same applies to the sector status fields.

The agreements are only used by radar positions. There is currently only one textbox per FIR and therefore should contain the relevant information for the whole FIR. We already allow S2 tower controllers to change these even though they are technically not a radar station. Agreements between ground stations are not relevant to radar stations and should be communicated individually or, if indeed relevant, added by the responsible radar controller.
